version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: warehouse-backend
    restart: always
    environment:
      POSTGRES_USER: postgres-wh
      POSTGRES_PASSWORD: postgres-wh123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
